services:
  - type: web
    name: poker-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: gunicorn app.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: app.settings
      - key: PYTHON_VERSION
        value: 3.10
